config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search', to: 'search#search'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user


	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end


  def self.search_for(content, how)
    if how == 'perfect'
      Book.where(title: content)
    elsif how == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif how == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    validates :comment, presence: true
    
    belongs_to :user
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, length: { in: 2..20 },
             uniqueness: true
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image


  has_many :books, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content,how)
    if how == 'perfect'
      User.where(name: content)
    elsif how == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif how == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.user_id = current_user.id
    @comment.save
  end


  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy

  end
end

private

def book_comment_params
  params.require(:book_comment).permit(:comment)
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :correct_book,only: [:edit]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
    @user = User.find_by(id: @book.user_id)
    @new_book = Book.new
   
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  def correct_book
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!


  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    # redirect_to request.referer
  end


  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end
  
  def followings
     user = User.find(params[:user_id])
     @users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end
  
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @how = params[:how]
    if @model == 'user'
      @records = User.search_for(@content,@how)
    elsif @model == 'book'
      @records = Book.search_for(@content,@how)
    end
  end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


   before_action :correct_user,only: [:edit]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new

  end



  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
       render action: :edit
    end
  end

  def correct_user
        @user = User.find(params[:id])
    unless @user.id == current_user.id
     # redirect_to user_path(@user)
      redirect_to user_path(current_user)
    end
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.folower
  end

  

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <table>
    <tr>
      <td>
        <%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %><br>
        <%= link_to book_comment.user.name,user_path(book_comment.user_id)  %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment),method: :delete, remote: true ,data: {confirm: "本当に消しますか？"},class: "btn btn-danger btn-sm"  %>
        <% end %>
      </td>
    </tr>
  </table>
<% end %>

app/views/book_comments/create.js.erb
$('#comments').html("<%= j(render 'comment_index',book: @book) %>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$('#comments').html("<%= j(render 'comment_index',book: @book) %>");
$("textarea").val('');

app/views/books/_comment.html.erb
  <div class="comment">
    <%= form_with model:[book,comment] do |f| %>
      <p>
        <%= f.text_area :comment, size: "90x5"%>
      </p>
      <%= f.submit "送信"%>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
      
      <h1>Editing Book</h1>
      
      <%= render 'layouts/error_form', user: @book %>
      
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label><br>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", class: "form-control" %>
        </div>
        
        <div class="form-group">
          <label for="inputOpinion">Opinion</label><br>
          <%= f.text_area :body, autofocus: true, id:"inputOpinion", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book',class: "btn btn-success" %>
        </div>
      <% end %>
      
      <%= link_to "Show", book_path(@book) %>
      <span>|</span>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <%= render 'layouts/error_form', user: @book %>
  <div class="row">
    <%= render 'layouts/sidebar', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
   <table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td id = "favorite_btn_<%= book.id %>">
              <%= render 'favorites/favorite_btn', book: book %>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/sidebar', book: @new_book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>

            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>

            <td id = 'favorite_btn_<%= @book.id %>'>
              <%= render 'favorites/favorite_btn', book: @book%>
            </td>

            <td>コメント件数：<%= @book.book_comments.count %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book),class: "btn btn-success" %></td>

            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"},class: "btn btn-danger" %></td>

            <% end %>
          </tr>
        </tbody>
      </table>
    <div id="comments">
      <%= render 'book_comments/comment_index',book: @book %>
    </div>
    <div id="user_comment">
      <%= render 'comment',book: @book, comment: @comment %>
    </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite_btn.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to "♥#{book.favorites.count}", book_favorites_path(book), method: :delete, remote: true, class: "text-danger" %>
  <% else %>
  <p>
    <%= link_to "♡#{book.favorites.count}", book_favorites_path(book), method: :post, remote: true, class: "text-primary" %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite_btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite_btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto">Welcome to <i class="fas fa-book"></i><sapn class="font-weight-bold">Bookers!</sapn></h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-6">
      <h1>welcome to<i class="fas fa-book"></i><sapn class="font-weight-bold">Bookers !!</sapn></h1>
    
      <p>In<span><i class="fas fa-book"></i></span>Bookers,</p>
    
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "col-12 btn btn-info  mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: "col-12 btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>
  

app/views/relationships/followers.erb
<div class="container-fluid">
  <h3>Follower Users</h3>

  <div class="row">
    <div class="col-12">
      <% if @users.empty? %>
        <p>ユーザーはいません</p>
      <% else %>
        <table width="100%">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @users.where.not(id: current_user.id).each do |user| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td><%= link_to "Show", user_path(user) %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/followings.erb
<div class="container-fluid">
  <h3>Follow Users</h3>
    <div class="row">
      <div class="col-12">
        <% if @users.empty? %>
          <p>ユーザーはいません</p>
        <% else %>
          <table width="100%">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <% @users.where.not(id: current_user.id).each do |user| %>
              <tbody>
                <tr>
                  <td>
                    <%= link_to user_path(user) do %>
                      <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
                    <% end %>
                  </td>
                  <td><%= user.name %></td>
                  <td>フォロー数：<%= user.followings.count %></td>
                  <td>フォロワー数：<%= user.followers.count %></td>
                  <td><%= link_to "Show", user_path(user) %></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
</div>

app/views/search/search.html.erb
<div class="container-fluid">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @records.each do |user| %>
        <tbody>
            <tr>
                <th>
                  <%= link_to follow_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @records.each do |book| %>
        <tbody>
            <tr>
                <th>
                  <%= link_to follow_path(book) do %>
                    <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
                  <% end %>
                </th>
                <th>
                    <%= book.title %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
    
    <h2>User info</h2>
    
    <%= render 'layouts/error_form', user: @user %>
    
    <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control" %>
      </div>
      
      <div class="form-group">
        <label for="inputImage">ProfileImage</label><br>
        <%= f.attachment_field :profile_image, autofocus: true, id:"inputImage", class: "form-control-file" %>
      </div>
      <div class="form-group">
        <label for="inputBody">introduction</label><br>
        <%= f.text_area :introduction, autofocus: true, id:"inputBody", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User",class: "btn btn-secondary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/following.erb
<div class="container-fluid">
  <h3>Follow Users</h3>
  <% if @users.empty? %>
    <p>ユーザーはいません</p>
  <% else %>
    <div class="row">
      <div class="col-12">
        <table width="100%">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @user.following_user.where.not(id: current_user.id).each do |user| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to follow_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, size: "90x90", fallback: "no_image.jpg", size: "90x90" %>
                  <% end %>
                </td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.follower.count %></td>
                <td>フォロワー数：<%= user.followed.count %></td>
                <td><%= link_to "Show", user_path(user) %></td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/sidebar', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
            <td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
            </td>
            <td><%= @user.name %></td>
            <td>フォロー数：<%= @user.relationships.count %></td>
            <td>フォロワー数：<%= @user.reverse_of_relationships.count %></td>
          </tr>
        <% @users.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
            </td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.relationships.count %></td>
            <td>フォロワー数：<%= user.reverse_of_relationships.count %></td>
            <td>

                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', user_relationships_path(user), method: :delete %>
                <% else %>
                  <%= link_to 'フォローする',user_relationships_path(user), method: :POST %>
                <% end %>

            </td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/sidebar', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
             <th>Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
              <%= link_to user_path(@user) do %>
                 <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></p></td>
              <td><%= book.body %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
              
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>