config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about', to: 'homes#about'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get '/search', to: 'search#search'
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user


	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end


  def self.search_for(content, how)
    if how == 'perfect'
      Book.where(title: content)
    elsif how == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif how == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    validates :comment, presence: true
    
    belongs_to :user
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, length: { in: 2..20 },
             uniqueness: true
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image


  has_many :books, dependent: :destroy
  has_many :book_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content,how)
    if how == 'perfect'
      User.where(name: content)
    elsif how == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif how == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end



  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :correct_book,only: [:edit]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
    @user = User.find_by(id: @book.user_id)
    @new_book = Book.new
   
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  def correct_book
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!


  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
    # redirect_to request.referer
  end


  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
    @content = params[:content]
    @how = params[:how]
    if @model == 'user'
      @records = User.search_for(@content,@how)
    elsif @model == 'book'
      @records = Book.search_for(@content,@how)
    end
  end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


   before_action :correct_user,only: [:edit]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new

  end



  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
       render action: :edit
    end
  end

  def correct_user
        @user = User.find(params[:id])
    unless @user.id == current_user.id
     # redirect_to user_path(@user)
      redirect_to user_path(current_user)
    end
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.folower
  end

  

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_form.html.erb
<% if user.errors.any? %>
 <div class="error-box">
    <h3 class="error-count text-danger">
      <% if user.errors.count == 1 %>
        <%= user.errors.count%>error prohibited this obj from being saved:</h3>
      <% else %>
        <%= user.errors.count%>errors prohibited this obj from being saved:</h3>
      <% end %>
      <% user.errors.full_messages.each do |message| %>
        <ul>
            <li class="error-text text-danger"><%= message %></li>
        </ul>
      <% end %>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<div class="row">
  <div class="col-md-12 text-center mt-md-1">
    <% if user_signed_in? %>
      <%= form_with url:search_path, method: :get, local: true do |f| %>
        <%= f.text_field :content %>
        <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= f.select :how, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"   }) %>
        <%= f.submit :"検索" %>                 
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-md-3">
  <h2 class="mb-2">User info</h2>

    <%= attachment_image_tag user, :profile_image, size: "90x90", format: 'jpeg', fallback: "no_image.jpg", size: "90x90" %>
    <table class="table">
      <thead>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>introduction</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td>follows</td>
          <td>
            <%= link_to @user.relationships.count, user_followings_path(@user) %>
          </td>
        </tr>
        <tr>
          <td>followers</td>
          <td>
            <%= link_to @user.reverse_of_relationships.count, user_followers_path(@user) %>
          </td>
        </tr>
      </tbody>
    </table>

      <% unless @user == current_user %>
        <% if current_user.following?(@user) %>
          <%= link_to 'フォロー外す', user_relationships_path(@user),class: "btn btn-primary btn-sm", method: :delete %>
        <% else %>
          <%= link_to 'フォローする',user_relationships_path(@user.id),class: "btn btn-success btn-sm", method: :POST %>
        <% end %>
      <% else %>
        <%= link_to edit_user_path(@user),class: "row" do %>
          <i class=" col-md-12 pull-right btn btn-outline-secondary btn-block fas fa-user-cog"></i>
        <% end %>
      <% end %>


  <h2>New  book</h2>
  <%= form_with model: book, local: true do |f| %>
    <p>
      <label for="inputTitle">Title</label><br>
      <%= f.text_field :title, autofocus: true, id:"inputTitle", size: "30x1" %>
    </p>
    <p>
      <label for="inputBody">Opinion</label><br>
      <%= f.text_area :body, autofocus: true, id:"inputBody", size: "30x3" %>
    </p>
      <%= f.submit "Create Book",class: "col-md-12 pull-right btn btn-success" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/9ebb9ecdaf.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar bg-dark navbar-expand-lg">
        <div class="container">
          <a href="/" class="navbar-brand text-light">Bookers</a>
          <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user.id),class: "nav-link text-light fas fa-home" %>
              </li>
              <li class="nav-item">
                <a href="/users" class="nav-link text-light fas fa-users"> Users</a>
              </li>
              <li class="nav-item">
                <a href="/books" class="nav-link text-light fas fa-book-open"> Books</a>
              </li>
              <li class="nav-item">
                <a href="/users/sign_out" data-method="delete"  class="nav-link text-light fas fa-sign-out-alt"> logout</a>
              </li>
            </ul>
          <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="/" class="nav-link text-light fas fa-home"> Home</a>
              </li>
              <li class="nav-item">
                <a href="/home/about" class="nav-link text-light fas fa-link"> About</a>
              </li>
              <li class="nav-item">
                <a href="/users/sign_up" class="nav-link text-light fas fa-user-plus"> sign up</a>
              </li>
              <li class="nav-item">
                <a href="/users/sign_in" class="nav-link text-light fas fa-sign-in-alt"> login</a>
              </li>
            </ul>
          <% end %>
        </div>
      </nav>
      <div class="container">
        <%= render 'layouts/search'%>
      </div>
    </header>

    <main class="mt-3">
      <% if flash[:notice] %>
        <p style="color: green;"><%= flash[:notice] %></p>
      <% end %>

          <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto ">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>